apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: nginx-example-base

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- ingress.yaml

commonLabels:
  app: nginx-example
  managed-by: argocd

images:
- name: nginx
  newTag: "1.25-alpine"
